### ISSUE TITLE
Cannot use `defineAction` outside `preset.ts` file

### ISSUE THREAD

**Issue by jcao02** [preset/preset#106] opened 2022-08-19 13:03 UTC
Hi!

Thanks for creating and maintaining this library. I think it has a very neat architecture that fosters code reusability through composition (unlike Yeoman or similar alternatives). However, I've found an implementation problem that could limit this feature and therefore adoption.

## Context
Node version: `16.13.0`
@preset/cli version: `0.6.1`
pnpm version: `7.9.0`

## Problem
When importing `defineAction` function (or anything from `@preset/core`) outside the file `preset.ts`, I get the following error:
```
require() of ES Module /Users/juan.arocha/.nvm/versions/node/v16.13.0/bin/5/.pnpm/execa@6.1.0/node_modules/execa/index.js from /Users/juan.arocha/.nvm/versions/node/v16.13.0/bin/5/.pnpm/@preset+core@0.6.1/node_modules/@preset/core/dist/index.js not supported.
```

Debugging a bit I found that the problem comes from the transpiled version of [this line of code](https://github.com/preset/preset/blob/642f244e82198da6fd8317c700cb9965142b9981/packages/core/src/utils.ts#L4), where a `require` is used to import an ESM module.

## Expected behaviour
It shouldn't throw an error

## Steps to reproduce
1. Create a file `my-action.ts` and add this code:
```ts
import { defineAction } from '@preset/core'

export const myAction = defineAction('my-action', async () => { /* ... */ })
```
2. Import it from `preset.ts`:
```ts
import { definePreset } from '@preset/core'
import { myAction } from './my-action'

export default definePreset({
  name: 'my-preset',
  handler: async () => {
    await myAction()
  },
})
```

## Workaround
In case someone needs a mitigation, there's a quick workaround which is exporting the action handler and create the action inside `preset.ts`:

```ts
// my-action.ts
import { ActionHandler } from '@preset/core'

export const myActionHandler: ActionHandler = async () => { /* ... */ }
```
```ts
// preset.ts
import { definePreset, defineAction } from '@preset/core'
import { myActionHandler } from './my-action'

const myAction = defineAction('my-action', myActionHandler)

export default definePreset({
  name: 'my-preset',
  handler: async () => {
    await myAction()
  },
})
```

**Comment by jcao02** [comment] 2022-08-19 13:53
Related to this: https://github.com/sindresorhus/execa/issues/489

**Comment by innocenzi** [comment] 2022-08-19 14:15
Hey, thanks for the report! I'm kind of aware of this issue, ESM-only packages are a real pain to work with. I'm trying to see how I can work around this.

**Comment by jcao02** [comment] 2022-08-19 14:33
I see. Did you consider perhaps downgrading `execa` to v5 as a short-term solution?

To be honest I think the best long-term approach is to move to pure ESM -- Node supports this for a while already and the TS version you use also does

**Comment by innocenzi** [comment] 2022-08-19 14:44
Yes I was considering moving to ESM as well, but the issue is that I use the `vm` API to run presets, and it doesn't work with ESM without a specific flag (https://nodejs.org/api/vm.html#class-vmmodule). 

I could probably work something out with `tsx` or `jiti`, but I don't really have bandwidth right now to try that out. 

I'm trying to inline ESM-only deps instead, but I have other issues with that too.

**Comment by innocenzi** [comment] 2022-08-19 15:22
Should be fixed with https://github.com/preset/preset/releases/tag/v0.7.0, but don't import `defineAction` from `@preset/core`, because it's not exported as a singleton, so the context will be missing. Simply use `defineAction` without importing anything and it should work.

**Closed as completed by innocenzi** 2022-08-19 15:22 UTC

**Comment by jcao02** [comment] 2022-08-19 15:31
Amazing! It worked. I was actually working on a PR downgrading both dependencies to the previous major versions 😅 

Thanks for handling this so quickly
