### ISSUE TITLE
SelectPromt Action doesn't handle `escape` & `ctrl +c`

### ISSUE THREAD

**Issue by jrson83** [preset/preset#129] opened 2024-04-27 17:52 UTC
Using the SeelectPrompt action, it is not possible to exit the process using `escape` or `ctrl +c`.

**Comment by innocenzi** [comment] 2024-04-27 18:47
Duplicate of #126, closing the previous one

**Comment by jrson83** [comment] 2024-04-27 19:20
This issue is not a duplicate of #126. This one is related to SelectPrompt, while the other is related to TextPrompt.
So the issue at the moment still persists, but I will push another commit to fix #126.

**Closed as completed** 2024-04-29 08:27 UTC
Labels: bug
